# Generated by Django 4.2.25 on 2025-10-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('crop_type', models.CharField(max_length=200)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres or hectares', max_digits=10)),
                ('area_unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares')], default='acres', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.TextField(help_text='Expected harvest or end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
