# Generated by Django 5.2.4 on 2025-11-16 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_budget_expense_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pest_control', 'Pest Control'), ('weeding', 'Weeding'), ('pruning', 'Pruning'), ('harvesting', 'Harvesting'), ('soil_test', 'Soil Test'), ('irrigation', 'Irrigation'), ('planting', 'Planting'), ('transplanting', 'Transplanting'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_days', models.IntegerField(default=0, help_text='Days before event to send reminder (0 = no reminder)')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='home.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crop Calendar Events',
                'ordering': ['date', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('preparation', 'Land Preparation'), ('planting', 'Planting'), ('germination', 'Germination'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('maturation', 'Maturation'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post-Harvest')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_stages', to='home.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crop Stages',
                'ordering': ['start_date', 'stage_name'],
            },
        ),
    ]
